<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>3903c67c-e242-40c7-801e-a2ac6d319049</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Factoring.Service.Application\Factoring.Service.Application.csproj" />
        <ProjectReference Include="..\Factoring.Service.Core\Factoring.Service.Core.csproj" />
        <ProjectReference Include="..\Factoring.Service.Infrastructure\Factoring.Service.Infrastructure.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
    </ItemGroup>
</Project>
